In [4]:
import numpy as np
import random


In [57]:
x= 4
streetgrid = np.genfromtxt('roadmap.csv',delimiter =',')
car_position = np.zeros((len(streetgrid),len(streetgrid)))
# for k in range(4):
for i in range(len(streetgrid)):
    for j in range(len(streetgrid)):
        if streetgrid[i,j] == 0:
            car_position[i,j] = 0
        elif streetgrid[i,j] == 1:
                    #car_position[4,j,0] = random.randint(0,x)
            car_position[7,j] = random.randint(0,x)
                #car_position[9,j,1] = random.randint(0,x)
                #car_position[i,9,3] = random.randint(0,x)
                #car_position[4,j,2] = random.randint(0,x)
                #car_position[i,4,3] = random.randint(0,x)
                #car_position[9,j,0] = random.randint(0,x)
                #car_position[i,9,2] = random.randint(0,x)

    
    
    



In [58]:
car_position

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.],
       [ 0.,  0.,  4.,  1.,  3.,  2.,  2.,  0.,  4.,  4.,  3.,  4.,  1.,
         0.,  4.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
       

In [91]:
car_position[7,3]

1.0

In [109]:
d = 4
right = 14
while dt for i in range(20):
    if i > right:
        i = 0
        car_position[7,i+1] = car_position[7,0]
    elif car_position[7,i] <= (d-car_position[7,i+1]):
        car_position[7,i+1] += car_position[7,i] 
        car_position[7,i] = 0
    else:
        car_position[7,i] = car_position[7,i] + (car_position[7,i+1]-d)
        car_position[7,i+1] = d
    print(car_position[7,i])
    
   



0.0
0.0
0.0
0.0
4.0
0.0
4.0
4.0
3.0
4.0
1.0
0.0
4.0
4.0


IndexError: index 15 is out of bounds for axis 1 with size 15

In [101]:
car_position[7,:]

array([ 0.,  0.,  4.,  1.,  3.,  2.,  2.,  0.,  4.,  4.,  3.,  4.,  1.,
        0.,  4.])

In [72]:
d-car_position[7,2]

0.0

In [69]:
car_position[7,1]<(d-car_position[7,2])

False

In [8]:
initial_traffic_position(4)

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 3.,  4.,  3.,  1.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  1.,  4.,  1.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 1.,  4.,  3.,  1.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 4.,  4.,  2.,  2.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
      